 name: "Checkov SAST Scan for Terraform .tfplan files as well as source code"
 
 on:
   workflow_dispatch:
   push:
     branches:
       - '*'
     paths:
       - ./**
   pull_request:
     branches:
       - main
     types:
       - opened
       - synchronize
     paths:
       - ./**
 
 permissions:
   contents: read
   id-token: write
   actions: read
   security-events: write
 
 jobs:
   sast-checkov-scan-plan:
     uses: UKHomeOffice/core-cloud-workflow-checkov-sast-scan/.github/workflows/checkov-scan-tfplan.yaml@a25892b307f06f1afabcee89dcfce9f849aa62b4 #1.14.5
     with:
      path: '.'
      
